# Zot Artifact Store - Minimal Configuration
# Quick start configuration for development and testing

# HTTP Server
http:
  address: 0.0.0.0
  port: "8080"

# Storage
storage:
  rootDirectory: /tmp/zot-artifacts

# Logging
log:
  level: info

# Note: Extension configuration will be added in a future update
# For now, all extensions are enabled with default settings
