apiVersion: v1
kind: Namespace
metadata:
  name: zot-operator-system
  labels:
    control-plane: zot-artifact-store-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot-artifact-store-operator
  namespace: zot-operator-system
  labels:
    app: zot-artifact-store-operator
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zot-artifact-store-operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: zot-artifact-store-operator
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: zot-artifact-store-operator

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: manager
          image: ghcr.io/candlekeep/zot-artifact-store-operator:latest
          imagePullPolicy: IfNotPresent

          command:
            - /manager

          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8080

          env:
            - name: WATCH_NAMESPACE
              value: ""  # Watch all namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zot-artifact-store-operator"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

      terminationGracePeriodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: zot-artifact-store-operator
                topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: zot-artifact-store-operator-metrics
  namespace: zot-operator-system
  labels:
    app: zot-artifact-store-operator
spec:
  selector:
    app: zot-artifact-store-operator
    control-plane: controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zot-artifact-store-operator
  namespace: zot-operator-system
  labels:
    app: zot-artifact-store-operator
spec:
  selector:
    matchLabels:
      app: zot-artifact-store-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
